### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by viper-sys** [panshujia/pcr-farm-script#8]
File "c:/Users/Viper/Desktop/pcr-farm-script-master/main.py", line 205
    time.sleep(4)
       ^
SyntaxError: invalid syntax

问一下这个是什么原因

**Comment by panshujia** [comment]
不小心传了有bug的版本上去。。已经重新上传了main.py函数

**Comment by viper-sys** [comment]
多谢作者了...我之前疑惑了好久为啥这个会报错

**Comment by viper-sys** [comment]
这个问题好像依旧是存在的。。是地下城跳过那一段的
        '''
        地下城战斗
        '''
        mainrunQuick(lines,['explor_blue','underground','normalUD','ok_blue']
        time.sleep(3)

顺便想问一下main.py的账号密码是需要‘ ’这个的嘛

**Comment by panshujia** [comment]
mainQuick那行最后少了一个括号，已经改了。。。。
对，账号需要‘’

**Comment by viper-sys** [comment]
发现了..十分感谢
